### ISSUE TITLE
使用无效,@import貌似插入点在最上面,下面引入了ant的themes把自己的变量又覆盖掉了

### ISSUE THREAD

**Issue by SquirrelJimmy** [yesmeck/webpack-less-theme-plugin#2]
![32c989e4-46d5-4003-a982-dfa4e55f45b8](https://user-images.githubusercontent.com/24666536/37082674-1ff8113e-2228-11e8-8812-804d315b1c18.png)

**Comment by yesmeck** [comment]
@sex-squirrel 有能重现的 repo 吗？
